import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} antialiased max-w-7xl mx-auto flex flex-col bg-yellow-100 min-h-screen`}
      >
        <header className="text-xl border-t-1 border-b-1 border-dashed border-gray-400 mx-1 mt-4 py-1 px-2 ">
          <h1>Yasiru Kassapa</h1>
        </header>
        <div className="flex-grow mt-4">{children}</div>
        <footer className="p-6 bg-gray-800 text-white">
          <div className="max-w-7xl mx-auto flex justify-between">
            <div className="text-sm">
              <p>&copy; {new Date().getFullYear()} Yasiru Kassapa</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
